"""Tab 5 — AI Analyst: Groq-backed chat grounded in the computed figures."""

from __future__ import annotations

import streamlit as st

from utils.llm_analyst import (
    DISCLAIMER,
    PRESET_BOARD_SUMMARY,
    PRESET_SUPPLIER_EMAIL,
    ask_analyst,
    get_model_name,
    groq_available,
)


def render(context: str) -> None:
    st.subheader("AI Analyst")

    if not groq_available():
        st.warning(
            "The AI Analyst is offline: no GROQ_API_KEY is configured. "
            "Add the key to the environment to enable this tab — all other "
            "tabs remain fully functional."
        )
        return

    st.caption(
        f"Answers are generated by `{get_model_name()}` strictly from the figures "
        "computed in this session — the current upload, EUA price and year selection."
    )

    if "chat_history" not in st.session_state:
        st.session_state["chat_history"] = []

    p1, p2 = st.columns(2)
    preset: str | None = None
    if p1.button("✉️ Draft supplier data request", width="stretch"):
        preset = PRESET_SUPPLIER_EMAIL
    if p2.button("📋 150-word board summary", width="stretch"):
        preset = PRESET_BOARD_SUMMARY

    for msg in st.session_state["chat_history"]:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    question = st.chat_input("Ask about the CBAM position…")
    if preset:
        question = preset

    if question:
        st.session_state["chat_history"].append({"role": "user", "content": question})
        with st.chat_message("user"):
            st.markdown(question)
        with st.chat_message("assistant"):
            try:
                with st.spinner("Analysing…"):
                    answer = ask_analyst(
                        context,
                        st.session_state["chat_history"][:-1],
                        question,
                    )
            except Exception as exc:  # noqa: BLE001 — API failures must not crash the app
                st.error(f"The analyst request failed: {exc}")
                st.session_state["chat_history"].pop()
                return
            st.markdown(answer)
        st.session_state["chat_history"].append({"role": "assistant", "content": answer})

    st.caption(f"_{DISCLAIMER}_")
